### ISSUE TITLE
Api stats for / Temp(Chip) / GH/S(RT) / Temp(PCB) /

### ISSUE THREAD

**Issue by Zwilla** [Zwilla/bmminer-cgminer492#3]
Working on Api Stats atm.

**Comment by Zwilla** [comment]
GH/S(RT) now fixed.

Working on:
Temp(Chip)
Temp(PCB) only temp 1 is working atm.
GH/S(RT) chain

**Comment by robertgochuco** [comment]
Hi. Im new to mining.. i have a bitmain antminer s9. can i use this to flash my antminer? will it still work like the bitmain console? will it work with cryptoglance? please advice. thank you.

**Comment by Zwilla** [comment]
https://shop.zwilla.de/en/antminer-s9-firmware-image.html

**Comment by davidromayPB** [comment]
Hi Guys, I'm new in github but I was wondering if soemone has the schematic or pcb files of Antminer S9.

I appreciate your answer.

Regards.
