### ISSUE TITLE
Is it possible to edit the way the antminer s7 hashes?

### ISSUE THREAD

**Issue by zoecarver** [Zwilla/bmminer-cgminer492#5]
I am wondering if it would be possible to change the way this machine hashes bitcoins. Would it be possible to change it from double SHA-256 to something like Ethash. If it is not possible, why? What would be some of the main reasons that it is impossible?

Thanks in advance!

**Comment by Ondalf** [comment]
No. ASIC that lies in the S7 or any BTC miner is designed to do single thing. To crack some sha256. It cannot be repurposed to any other hash algorithm. Changing algorithm basically means changing chip that knows, how to do something else than just sha256 in this matter. And no, those can't be reprogrammed. Those are ASICs. Means that they do just single thing in their life. Nothing else.
