### ISSUE TITLE
Build problem; appears to be autotools failing to load C std lib headers

### ISSUE THREAD

**Issue by shefft** [Zwilla/bmminer-cgminer492#8]
Have followed the build.md build instructions, as well as attempted numerous other approaches.  This problem occurs on compiles for both native and armhf target.

The configuration step seems to complete in a satisfactory way. When I run make, I'm shown a set of errors primarily of these types:
```
error: ‘TRUE’ undeclared here (not in a function)
error: ‘struct work’ has no member named ‘version’
error: expected ‘)’ before ‘PRIu64’
```
Let's focus on the last one, which I have spent time researching - and I suspect all the errors are related to missing definitions. Apparently the print-friendly extended definitions from the C standard library header file inttypes.h is not being found. However, in the configure step everything is claimed to be in order:
```
configure:4930: checking for inttypes.h
configure:4930: /usr/bin/x86_64-linux-gnu-gcc -c -g -O2  conftest.c >&5
configure:4930: $? = 0
configure:4930: result: yes
```
All the INTTYPES flags are set correctly if I look in confdefs.h, config.h, config.log Output Variables, etc:
```
HAVE_INTTYPES_H='1'
#define HAVE_INTTYPES_H 1
```
I've confirmed that the -DHAVE_CONFIG_H mechanic looks good through configure, config.log, Makefile, etc.  The problem is the same whether doing a native build, or cross-compiling (for arm-linux-gnueabihf, aka armhf).

The source .c file in question does have config.h included as you'd expect, which by my understanding via the m4 macros mechanic should be adding an

`#include <inttypes.h>`

line. Yes, as you may be inclined to ask, if I enter this line myself into the .c file it appears to work and the PRIu64 errors go away.

**Comment by shefft** [comment]
It appears that these lines are missing from cgminer.c:
#ifdef HAVE_INTTYPES_H
#include <inttypes.h>
#endif
as the autotools will not generate these include directives automatically.  Probably something similar missing for the other error types as well.

**Comment by Zwilla** [comment]
Have build this not on a toolchain, it was build on antminer direct
